[2022-08-19 15:00:03,125] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 scheduled__2022-08-18T14:55:00+00:00 [queued]>
[2022-08-19 15:00:03,135] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 scheduled__2022-08-18T14:55:00+00:00 [queued]>
[2022-08-19 15:00:03,136] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 15:00:03,136] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-19 15:00:03,137] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 15:00:03,148] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr1> on 2022-08-18 14:55:00+00:00
[2022-08-19 15:00:03,155] {standard_task_runner.py:52} INFO - Started process 4626 to run task
[2022-08-19 15:00:03,160] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr1', 'scheduled__2022-08-18T14:55:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmptwu02nb9', '--error-file', '/tmp/tmphmpy4h4p']
[2022-08-19 15:00:03,162] {standard_task_runner.py:80} INFO - Job 140: Subtask cr1
[2022-08-19 15:00:03,244] {task_command.py:371} INFO - Running <TaskInstance: craw.cr1 scheduled__2022-08-18T14:55:00+00:00 [running]> on host 0d2dcb932a96
[2022-08-19 15:00:03,324] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr1
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T14:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-18T14:55:00+00:00
[2022-08-19 15:00:03,393] {base.py:68} INFO - Using connection ID 'mysql' for task execution.
[2022-08-19 15:00:03,397] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/newtest.py", line 39, in crawling
    conn= mysql_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 166, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 932, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/_auth.py", line 239, in caching_sha2_password_auth
    pkt = conn._read_packet()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database '***'")
[2022-08-19 15:00:03,417] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=craw, task_id=cr1, execution_date=20220818T145500, start_date=20220819T150003, end_date=20220819T150003
[2022-08-19 15:00:03,439] {standard_task_runner.py:92} ERROR - Failed to execute job 140 for task cr1 ((1049, "Unknown database '***'"); 4626)
[2022-08-19 15:00:03,492] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-19 15:00:03,542] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
