[2022-08-18 04:39:01,164] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-18T04:38:28.162136+00:00 [queued]>
[2022-08-18 04:39:01,237] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-18T04:38:28.162136+00:00 [queued]>
[2022-08-18 04:39:01,245] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 04:39:01,254] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-18 04:39:01,255] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 04:39:01,358] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr1> on 2022-08-18 04:38:28.162136+00:00
[2022-08-18 04:39:01,401] {standard_task_runner.py:52} INFO - Started process 2127 to run task
[2022-08-18 04:39:01,437] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr1', 'manual__2022-08-18T04:38:28.162136+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmppregxfkp', '--error-file', '/tmp/tmpq5r9ovmb']
[2022-08-18 04:39:01,443] {standard_task_runner.py:80} INFO - Job 180: Subtask cr1
[2022-08-18 04:39:01,812] {task_command.py:371} INFO - Running <TaskInstance: craw.cr1 manual__2022-08-18T04:38:28.162136+00:00 [running]> on host d59619969b18
[2022-08-18 04:39:02,398] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr1
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T04:38:28.162136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T04:38:28.162136+00:00
[2022-08-18 04:39:12,682] {base.py:68} INFO - Using connection ID 'mysql' for task execution.
[2022-08-18 04:39:12,709] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-18 04:39:13,540] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-18 04:39:14,311] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-18 04:39:53,781] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/newtest.py", line 60, in crawling
    scroll=driver.find_element(By.XPATH,'//*[@id="__next"]/div/div[2]/div[2]/div[3]/div[1]/ul/div/div[{}]/li/div/div[2]/div[1]/a'.format(i))
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 859, in find_element
    'value': value})['value']
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="__next"]/div/div[2]/div[2]/div[3]/div[1]/ul/div/div[1]/li/div/div[2]/div[1]/a"}
  (Session info: headless chrome=104.0.5112.79)
Stacktrace:
#0 0x557ac6000403 <unknown>
#1 0x557ac5e06778 <unknown>
#2 0x557ac5e3dc87 <unknown>
#3 0x557ac5e3de51 <unknown>
#4 0x557ac5e70f24 <unknown>
#5 0x557ac5e5ba2d <unknown>
#6 0x557ac5e6ec74 <unknown>
#7 0x557ac5e5b8f3 <unknown>
#8 0x557ac5e310d8 <unknown>
#9 0x557ac5e32205 <unknown>
#10 0x557ac6047e3d <unknown>
#11 0x557ac604adb6 <unknown>
#12 0x557ac603113e <unknown>
#13 0x557ac604b9b5 <unknown>
#14 0x557ac6025970 <unknown>
#15 0x557ac6068228 <unknown>
#16 0x557ac60683bf <unknown>
#17 0x557ac6082abe <unknown>
#18 0x7fa9eb630ea7 <unknown>

[2022-08-18 04:39:54,224] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=craw, task_id=cr1, execution_date=20220818T043828, start_date=20220818T043901, end_date=20220818T043954
[2022-08-18 04:39:54,362] {standard_task_runner.py:97} ERROR - Failed to execute job 180 for task cr1 (Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="__next"]/div/div[2]/div[2]/div[3]/div[1]/ul/div/div[1]/li/div/div[2]/div[1]/a"}
  (Session info: headless chrome=104.0.5112.79)
Stacktrace:
#0 0x557ac6000403 <unknown>
#1 0x557ac5e06778 <unknown>
#2 0x557ac5e3dc87 <unknown>
#3 0x557ac5e3de51 <unknown>
#4 0x557ac5e70f24 <unknown>
#5 0x557ac5e5ba2d <unknown>
#6 0x557ac5e6ec74 <unknown>
#7 0x557ac5e5b8f3 <unknown>
#8 0x557ac5e310d8 <unknown>
#9 0x557ac5e32205 <unknown>
#10 0x557ac6047e3d <unknown>
#11 0x557ac604adb6 <unknown>
#12 0x557ac603113e <unknown>
#13 0x557ac604b9b5 <unknown>
#14 0x557ac6025970 <unknown>
#15 0x557ac6068228 <unknown>
#16 0x557ac60683bf <unknown>
#17 0x557ac6082abe <unknown>
#18 0x7fa9eb630ea7 <unknown>
; 2127)
[2022-08-18 04:39:54,437] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-18 04:39:54,586] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
