[2022-08-11 02:37:09,719] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T02:28:35.663834+00:00 [queued]>
[2022-08-11 02:37:09,735] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T02:28:35.663834+00:00 [queued]>
[2022-08-11 02:37:09,736] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 02:37:09,737] {taskinstance.py:1377} INFO - Starting attempt 3 of 3
[2022-08-11 02:37:09,738] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 02:37:09,763] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr1> on 2022-08-11 02:28:35.663834+00:00
[2022-08-11 02:37:09,775] {standard_task_runner.py:52} INFO - Started process 1693 to run task
[2022-08-11 02:37:09,784] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr1', 'manual__2022-08-11T02:28:35.663834+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmpaf_5nj9l', '--error-file', '/tmp/tmpb4qfnqtb']
[2022-08-11 02:37:09,787] {standard_task_runner.py:80} INFO - Job 54: Subtask cr1
[2022-08-11 02:37:09,977] {task_command.py:371} INFO - Running <TaskInstance: craw.cr1 manual__2022-08-11T02:28:35.663834+00:00 [running]> on host d59619969b18
[2022-08-11 02:37:10,155] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr1
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T02:28:35.663834+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T02:28:35.663834+00:00
[2022-08-11 02:37:10,158] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-11 02:37:10,399] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-11 02:37:11,027] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-11 02:37:12,031] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/newtest.py", line 107, in craw1
    crawling(1,3)
  File "/opt/airflow/dags/newtest.py", line 42, in crawling
    driver.get('https://search.shopping.naver.com/search/all?query=%ED%82%A4%EB%B3%B4%EB%93%9C&frm=NVSHATC&prevQuery=%ED%82%A4%EB%B3%B4%EB%93%9C')
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 447, in get
    self.execute(Command.GET, {'url': url})
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=104.0.5112.79)
Stacktrace:
#0 0x55a4621fe403 <unknown>
#1 0x55a462004778 <unknown>
#2 0x55a461ffe565 <unknown>
#3 0x55a461ff2296 <unknown>
#4 0x55a461ff3232 <unknown>
#5 0x55a461ff2562 <unknown>
#6 0x55a461ff1995 <unknown>
#7 0x55a461ff065b <unknown>
#8 0x55a461ff0ac2 <unknown>
#9 0x55a4620061e2 <unknown>
#10 0x55a46206d3cf <unknown>
#11 0x55a462059a02 <unknown>
#12 0x55a46206cc74 <unknown>
#13 0x55a4620598f3 <unknown>
#14 0x55a46202f0d8 <unknown>
#15 0x55a462030205 <unknown>
#16 0x55a462245e3d <unknown>
#17 0x55a462248db6 <unknown>
#18 0x55a46222f13e <unknown>
#19 0x55a4622499b5 <unknown>
#20 0x55a462223970 <unknown>
#21 0x55a462266228 <unknown>
#22 0x55a4622663bf <unknown>
#23 0x55a462280abe <unknown>
#24 0x7f7628099ea7 <unknown>

[2022-08-11 02:37:12,069] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=craw, task_id=cr1, execution_date=20220811T022835, start_date=20220811T023709, end_date=20220811T023712
[2022-08-11 02:37:12,103] {standard_task_runner.py:97} ERROR - Failed to execute job 54 for task cr1 (Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=104.0.5112.79)
Stacktrace:
#0 0x55a4621fe403 <unknown>
#1 0x55a462004778 <unknown>
#2 0x55a461ffe565 <unknown>
#3 0x55a461ff2296 <unknown>
#4 0x55a461ff3232 <unknown>
#5 0x55a461ff2562 <unknown>
#6 0x55a461ff1995 <unknown>
#7 0x55a461ff065b <unknown>
#8 0x55a461ff0ac2 <unknown>
#9 0x55a4620061e2 <unknown>
#10 0x55a46206d3cf <unknown>
#11 0x55a462059a02 <unknown>
#12 0x55a46206cc74 <unknown>
#13 0x55a4620598f3 <unknown>
#14 0x55a46202f0d8 <unknown>
#15 0x55a462030205 <unknown>
#16 0x55a462245e3d <unknown>
#17 0x55a462248db6 <unknown>
#18 0x55a46222f13e <unknown>
#19 0x55a4622499b5 <unknown>
#20 0x55a462223970 <unknown>
#21 0x55a462266228 <unknown>
#22 0x55a4622663bf <unknown>
#23 0x55a462280abe <unknown>
#24 0x7f7628099ea7 <unknown>
; 1693)
[2022-08-11 02:37:12,131] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-11 02:37:12,213] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
