[2022-08-18 04:39:03,817] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr2 manual__2022-08-18T04:38:28.162136+00:00 [queued]>
[2022-08-18 04:39:03,934] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr2 manual__2022-08-18T04:38:28.162136+00:00 [queued]>
[2022-08-18 04:39:03,947] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 04:39:03,948] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-18 04:39:03,949] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 04:39:04,078] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr2> on 2022-08-18 04:38:28.162136+00:00
[2022-08-18 04:39:04,106] {standard_task_runner.py:52} INFO - Started process 2128 to run task
[2022-08-18 04:39:04,147] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr2', 'manual__2022-08-18T04:38:28.162136+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmpxx3jdk_i', '--error-file', '/tmp/tmp16z722l_']
[2022-08-18 04:39:04,186] {standard_task_runner.py:80} INFO - Job 181: Subtask cr2
[2022-08-18 04:39:04,828] {task_command.py:371} INFO - Running <TaskInstance: craw.cr2 manual__2022-08-18T04:38:28.162136+00:00 [running]> on host d59619969b18
[2022-08-18 04:39:05,550] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr2
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T04:38:28.162136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-18T04:38:28.162136+00:00
[2022-08-18 04:39:05,655] {base.py:68} INFO - Using connection ID 'mysql' for task execution.
[2022-08-18 04:39:05,856] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-18 04:39:07,714] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-18 04:39:53,098] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
