[2022-08-11 04:48:27,586] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T04:48:21.621599+00:00 [queued]>
[2022-08-11 04:48:27,677] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T04:48:21.621599+00:00 [queued]>
[2022-08-11 04:48:27,691] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 04:48:27,694] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-11 04:48:27,709] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 04:48:27,878] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr1> on 2022-08-11 04:48:21.621599+00:00
[2022-08-11 04:48:27,907] {standard_task_runner.py:52} INFO - Started process 10823 to run task
[2022-08-11 04:48:27,919] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr1', 'manual__2022-08-11T04:48:21.621599+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmphaa7b1iz', '--error-file', '/tmp/tmphah7oy7d']
[2022-08-11 04:48:27,933] {standard_task_runner.py:80} INFO - Job 68: Subtask cr1
[2022-08-11 04:48:28,334] {task_command.py:371} INFO - Running <TaskInstance: craw.cr1 manual__2022-08-11T04:48:21.621599+00:00 [running]> on host d59619969b18
[2022-08-11 04:48:29,032] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr1
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T04:48:21.621599+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T04:48:21.621599+00:00
[2022-08-11 04:48:29,036] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-11 04:48:29,660] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-11 04:48:31,801] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-11 04:51:14,477] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/newtest.py", line 93, in crawling
    driver.close()
NameError: name 'lists' is not defined
[2022-08-11 04:51:14,549] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=craw, task_id=cr1, execution_date=20220811T044821, start_date=20220811T044827, end_date=20220811T045114
[2022-08-11 04:51:14,613] {standard_task_runner.py:97} ERROR - Failed to execute job 68 for task cr1 (name 'lists' is not defined; 10823)
[2022-08-11 04:51:14,722] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-11 04:51:14,817] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
