[2022-08-11 04:43:04,834] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T04:35:17.364741+00:00 [queued]>
[2022-08-11 04:43:04,858] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T04:35:17.364741+00:00 [queued]>
[2022-08-11 04:43:04,858] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 04:43:04,859] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-11 04:43:04,860] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 04:43:04,891] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr1> on 2022-08-11 04:35:17.364741+00:00
[2022-08-11 04:43:04,903] {standard_task_runner.py:52} INFO - Started process 10394 to run task
[2022-08-11 04:43:04,910] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr1', 'manual__2022-08-11T04:35:17.364741+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmp7pw9g79u', '--error-file', '/tmp/tmp30tnnfm8']
[2022-08-11 04:43:04,913] {standard_task_runner.py:80} INFO - Job 67: Subtask cr1
[2022-08-11 04:43:05,143] {task_command.py:371} INFO - Running <TaskInstance: craw.cr1 manual__2022-08-11T04:35:17.364741+00:00 [running]> on host d59619969b18
[2022-08-11 04:43:05,399] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr1
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T04:35:17.364741+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T04:35:17.364741+00:00
[2022-08-11 04:43:05,403] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-11 04:43:05,638] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-11 04:43:06,929] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-11 04:45:44,869] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/newtest.py", line 93, in crawling
    lists.append((image, name, price, review))
NameError: name 'lists' is not defined
[2022-08-11 04:45:44,907] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=craw, task_id=cr1, execution_date=20220811T043517, start_date=20220811T044304, end_date=20220811T044544
[2022-08-11 04:45:44,949] {standard_task_runner.py:97} ERROR - Failed to execute job 67 for task cr1 (name 'lists' is not defined; 10394)
[2022-08-11 04:45:44,985] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-11 04:45:45,088] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
